### ISSUE TITLE
Need of remarks to be entered by user authorizing the report

### ISSUE THREAD

**Issue by PrabhaChalanatha** [lk-gov-health-hiu/clims#33]
Need of remarks to be entered by the user authorizing the report. In case of commenting suggestions regarding the report

![need of remarcks ](https://user-images.githubusercontent.com/74244684/199441297-891b60b5-fc11-4144-bbcf-00249bae6dc5.png)

**Comment by buddhika75** [comment]
You can add it to the report format.
